<?php if ($this->pageCount):?>

<ul class="pagination ">

    <!-- First page link -->
    <li<?php echo (isset($this->previous)) ? '' : ' class="disabled"'; ?>>
        <a href="<?php echo $this->url('zfcuser/zfcuserlist', array('p' => $this->first)); ?>">&lt;&lt; First</a>
    </li>

    <!-- Previous page link -->
    <li<?php echo (isset($this->previous)) ? '' : ' class="disabled"'; ?>>
        <a href="<?php echo $this->url('zfcuser/zfcuserlist', array('p' => $this->previous-$this->itemCountPerPage+1)); ?>">&lt; Previous <?php echo $this->itemCountPerPage; ?></a>
    </li>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
    <li<?php echo ($page == $this->current) ? ' class="active"' : ''; ?>>
        <a href="<?php echo $this->url('zfcuser/zfcuserlist', array('p' => $page)); ?>"><?php echo $page; ?></a>
    </li>
    <?php endforeach; ?>

    <!-- Next page link -->
    <li<?php echo (isset($this->next)) ? '' : ' class="disabled"'; ?>>
        <a href="<?php echo $this->url('zfcuser/zfcuserlist', array('p' => $this->next+$this->itemCountPerPage-1)); ?>">Next <?php echo $this->itemCountPerPage; ?> &gt;</a>
    </li>

    <!-- Last page link -->
    <li<?php echo (isset($this->next)) ? '' : ' class="disabled"'; ?>>
        <a href="<?php echo $this->url('zfcuser/zfcuserlist', array('p' => $this->last)); ?>">Last &gt;&gt;</a>
    </li>

</ul>

<?php endif; ?>

<?php
$script = $this->inlineScript();
$script->appendScript(<<<'EOT'

$(".pagination .disabled a").click(function() {
  return false;
});

EOT
);
